### PR TITLE
Update to 1.13

### PR DESCRIPTION
**Pull request by jonashaag**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonashaag** [comment]
@conda-forge-admin, please rerender

**Comment by jonashaag** [comment]
@conda-forge-admin, please rerender

**Comment by jonashaag** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fb5145965ef in dl_main () from /lib64/ld-linux-x86-64.so.2
#0  0x00007fb5145965ef in dl_main () from /lib64/ld-linux-x86-64.so.2
#1  0x00007fb5145ab00e in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#2  0x00007fb514594bd1 in _dl_start () from /lib64/ld-linux-x86-64.so.2
#3  0x00007fb514594148 in _start () from /lib64/ld-linux-x86-64.so.2
#4  0x0000000000000002 in ?? ()
#5  0x00007ffc621f38a7 in ?? ()
#6  0x00007ffc621f39b0 in ?? ()
#7  0x0000000000000000 in ?? ()
```

**Comment by 0xbe7a** [comment]
@conda-forge-admin, please restart ci

**Comment by jonashaag** [comment]
@0xbe7a the segfault is reproducible with 1.13 and 1.14. Maybe something wrong with glibc version?

**Comment by jonashaag** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@jonashaag All 🍏 here.

**Comment by jonashaag** [comment]
Thank you!

**Pull request closed without merging**
